apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dori4-replicaset
  labels:
    app: dori4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dori4
  template:
    metadata:
      labels:
        app: dori4
    spec:        
      containers:
      - name: lab4-container
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: env-cm
              key: ReactAppUserName
        - name: REACT_APP_COMPANY_NAME
          valueFrom:
            configMapKeyRef:
              name: env-cm
              key: ReactAppCompanyName