apiVersion: v1
kind: Service
metadata:
  name: lab4-service
spec:
  selector:
    app: dori4
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 3000
      