apiVersion: v1
kind: Service
metadata:
  labels:
    app: dori
  name: dori
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: dori
  type: LoadBalancer