apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dori3
  labels:
    app: dori3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dori3
  template:
    metadata:
      labels:
        app: dori3
    spec:
      containers:
      - image: ifilyaninitmo/itdt-contained-frontend:master
        name: master
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: dori3-cm